ame: Kite Alert Bot

on:
  schedule:
    - cron: "0 6,18 * * *"   # Runs automatically at 06:00 & 18:00 UTC
  workflow_dispatch:          # Lets you run manually from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python kite_alert_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
